### ISSUE TITLE
无法导入Bar模块

### ISSUE THREAD

**Issue by Hudi233** [chenjiandongx/pyecharts#1]
嗨，我在使用的时候完全是copy测试代码来执行的，安装步骤是先装了Image 然后在装的pyecharts，但是执行文件的时候报错：ImportError: cannot import name Bar。请问是怎么回事呢？

**Comment by chenjiandongx** [comment]
试试 pip install pyecharts==0.1.5 或者 sudo pip install pyecharts==0.1.5

**Comment by Hudi233** [comment]
成功了，谢谢！我之前安装的版本，默认输入pyecharts的话是0.1.4。多谢！

**Comment by nicoleyu0623** [comment]
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "/private/var/folders/mh/clj35gdd5cb1yfxthzzxl0fr0000gn/T/pip-install-bdjt5_ss/pyecharts/pyecharts/charts/scatter.py", line 5, in <module>
        from PIL import Image
    ModuleNotFoundError: No module named 'PIL'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mh/clj35gdd5cb1yfxthzzxl0fr0000gn/T/pip-install-bdjt5_ss/pyecharts/setup.py", line 6, in <module>
        import pyecharts.__version__ as about
      File "/private/var/folders/mh/clj35gdd5cb1yfxthzzxl0fr0000gn/T/pip-install-bdjt5_ss/pyecharts/pyecharts/__init__.py", line 5, in <module>
        from pyecharts.charts.effectscatter import EffectScatter
      File "/private/var/folders/mh/clj35gdd5cb1yfxthzzxl0fr0000gn/T/pip-install-bdjt5_ss/pyecharts/pyecharts/charts/effectscatter.py", line 4, in <module>
        from pyecharts.charts.scatter import Scatter
      File "/private/var/folders/mh/clj35gdd5cb1yfxthzzxl0fr0000gn/T/pip-install-bdjt5_ss/pyecharts/pyecharts/charts/scatter.py", line 7, in <module>
        import Image
    ModuleNotFoundError: No module named 'Image'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mh/clj35gdd5cb1yfxthzzxl0fr0000gn/T/pip-install-bdjt5_ss/pyecharts/

**Comment by sunhailin-Leo** [comment]
@nicoleyu0623 Make sure your python environment install `Pillow` already.

**Comment by ahbon123** [comment]
安装了pyecharts==0.1.5和pyecharts==0.1.4，还是不行

**Comment by laozhongyi-0326** [comment]
我安装的1.6

**Comment by sunhailin-Leo** [comment]
@laozhongyi-0326 看文档谢谢~ [文档](https://pyecharts.org/)

**Comment by laozhongyi-0326** [comment]
@sunhailin-Leo 谢谢

**Comment by laozhongyi-0326** [comment]
![image](https://user-images.githubusercontent.com/34592750/68838965-a949d400-06fa-11ea-969d-59a355ee99a3.png)
