### ISSUE TITLE
'NoneType' object has no attribute 'append'

### ISSUE THREAD

**Issue by sooluck** [chenjiandongx/pyecharts#116]
overlap.add(line)
overlap.add(line2,xaxis_index=1,is_add_xaxis=True)
overlap.render()

报错：
Traceback (most recent call last):
  File "c:\Users\\HelloMycode\Python\StartUp\WxSportsDataAnlynsis.py", line 73, in <module>
    overlap.add(line2,xaxis_index=1,is_add_xaxis=True)
  File "C:\Users\\AppData\Local\Programs\Python\Python35\lib\site-packages\pyecharts\custom\overlap.py", line 38, in add
    self.__custom(_series)
  File "C:\Users\\AppData\Local\Programs\Python\Python35\lib\site-packages\pyecharts\custom\overlap.py", line 54, in __custom
    self._chart._option.get('xAxis').append(_xaxis)
AttributeError: 'NoneType' object has no attribute 'append'

**Comment by chenjiandongx** [comment]
请贴上所有代码

**Comment by sooluck** [comment]
...有点迷，重新写了测试用例没有复现。可能是我之前写的有点问题，不好意思。
