### ISSUE TITLE
ImportError: cannot import name Line 问题

### ISSUE THREAD

**Issue by cvood** [chenjiandongx/pyecharts#176]
代码如下
```
#!/usr/bin/python
#coding=utf-8
from __future__ import unicode_literals
from pyecharts import Line
import re

text = open('vd5.txt','r')
data = {}

for line in text.xreadlines():

	if '2017' in line:
		data['date'].append(re.findall(r'[0-9]+-[0-9]+-[0-9]+',line))
	elif 'Ccp.clientsolutions.cn' in line:
		f_key = 'ccp'
	elif 'Lb.clientsolutions.cn' in line:
		f_key = 'lb'
	elif 'Mysql.clientsolutions.cn' in line:
		f_key = 'mysql'
	elif 'Redis.clientsolutions.cn' in line:
		f_key = 'redis'
	elif len(line.strip()) == 0:
		continue
	else:
		s_key = findall(r'vd[a-z]1?',line)
		key = f_key&'_'&s_key
		value = findall(r'[0-9]+%',line)
		if key in data:
			data[key].append(value)
		else:
			data[key] = []
			data[key].append(value)
text.close()

ect_line = Line('test')
ect_line.add('ccp_vda1',data['date'],data['ccp_vda1'],mark_point=["average"])
ect_line.add('ccp_vdb1',data['date'],data['ccp_vdb1'],mark_point=["average"])
ect_line.render()

```
用文档中的例子就可以成功生成html，也有图像，我自己的代码就有这个问题。
我学python没多久，也没什么编程经验，怎么也找不到问题，百度了很久也没解决，希望大神的指点迷津。

**Comment by chenjiandongx** [comment]
@cvood 用文档中的例子可以正常显示，用自己的就 can‘t import?

**Comment by cvood** [comment]
@chenjiandongx  是的，我试了好几次都是这样，不知道是不是我代码有什么问题。

**Comment by chenjiandongx** [comment]
can't import 有两个原因
1. pyecharts 没安装成功
2. pyecharts 安装成功但是没有运行在同一个 python 环境

**Comment by cvood** [comment]
但是我只安装了Python2.7,而且官方的例子也运行成功了啊？应该不会是没有安装成功吧。

**Comment by chenjiandongx** [comment]
贴上完整代码及错误信息

**Comment by cvood** [comment]
抱歉，现在不是自己电脑，等晚上贴上，到时候再麻烦你了，谢谢。

**Comment by chenjiandongx** [comment]
OK

**Comment by chfw** [comment]
能贴上所有的stack trace更好。

**Comment by cvood** [comment]
```
Traceback (most recent call last):
  File "C:\Users\cp123\Documents\�ҵļ����\pyecharts.py", line 4, in <module>
    from pyecharts import Line
  File "C:\Users\cp123\Documents\�ҵļ����\pyecharts.py", line 4, in <module>
    from pyecharts import Line
ImportError: cannot import name Line
[Finished in `0.306s]
```
这是错误信息，我还发现一个神奇的情况，当我自己的脚本和例子在同一个文件夹的时候也会出问题。
```
Traceback (most recent call last):
  File "C:\Users\cp123\Documents\example.py", line 2, in <module>
    from pyecharts import Bar
  File "C:\Users\cp123\Documents\pyecharts.py", line 4, in <module>
    from pyecharts import Line
ImportError: cannot import name Line
    from pyecharts import Bar
  File "C:\Users\cp123\Documents\pyecharts.py", line 4, in <module>
    from pyecharts import Line
ImportError: cannot import name Line
[Finished in 0.25s]
[Finished in 0.282s]

```

**Comment by chenjiandongx** [comment]
@cvood 不要把文件命名为 pyecharts.py 换为别的

**Comment by cvood** [comment]
谢谢大神，问题解决了，这么低级的错误我居然都没想到。
