### ISSUE TITLE
Linux Mint 底下安装问题

### ISSUE THREAD

**Issue by Jackcoolman** [chenjiandongx/pyecharts#2]
环境：Linux Mint
Python版本： Both 2.7 and 3.4
问题：貌似是Pip源的问题，换到清华的时候，无法安装，是不是找错东西了？
 $ pip3 install pyecharts
Collecting pyecharts
Collecting Image (from pyecharts)
Collecting pprint (from pyecharts)
Collecting django (from Image->pyecharts)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/fe/ca/a7b35a0f5088f26b1ef3c7add57161a7d387a4cbd30db01c1091aa87e207/Django-1.11.3-py2.py3-none-any.whl
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from Image->pyecharts)
Requirement already satisfied: pytz in /usr/local/lib/python3.5/dist-packages (from django->Image->pyecharts)
Installing collected packages: django, Image, pprint, pyecharts
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.5/dist-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python3.5/dist-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python3.5/dist-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/usr/local/lib/python3.5/dist-packages/Django-1.11.3.dist-info'

**Comment by Jackcoolman** [comment]
root权限下安装，直接提示
Collecting pyecharts

No matching distribution found for pyecharts
 requirement pyecharts (from versions: )

**Comment by chenjiandongx** [comment]
试试 sudo install pyecharts==0.1.5

**Comment by Jackcoolman** [comment]
问题解决,不能用su安装,得用
 $ pip install pyecharts --user
多谢!

**Comment by chenjiandongx** [comment]
没问题的话我就把这个issue关了哈
